name: Continuous Integration - googlecloudspanner

on:
  workflow_run:
    workflows: [Continuous Integration]
    types:
      - completed

jobs:
  release:
    name: Continuous Integration - googlecloudspanner - GoReleaser
    uses: ./.github/workflows/base-goreleaser-ci.yaml
    with:
      distribution: googlecloudspanner
    secrets: inherit
