name: Continuous Integration - gitlab

on:
  workflow_dispatch:
  # workflow_run:
  #   workflows: [Continuous Integration]
  #   types:
  #     - completed

jobs:
  release:
    name: Continuous Integration - gitlab - GoReleaser
    uses: ./.github/workflows/base-goreleaser-ci.yaml
    with:
      distribution: gitlab
    secrets: inherit
