name: Continuous Integration - githubactions

on:
  workflow_run:
    workflows: [Continuous Integration]
    types:
      - completed

jobs:
  release:
    name: Continuous Integration - githubactions - GoReleaser
    uses: ./.github/workflows/base-goreleaser-ci.yaml
    with:
      distribution: githubactions
    secrets: inherit
