name: Release gitlab

on:
  workflow_dispatch:
  # release:
  #   types: [published]

jobs:
  release:
    name: Release gitlab
    uses: ./.github/workflows/base-release.yaml
    with:
      distribution: gitlab
    secrets: inherit
    permissions: write-all
