name: Release googlecloudspanner

on:
  release:
    types: [published]

jobs:
  release:
    name: Release googlecloudspanner
    uses: ./.github/workflows/base-release.yaml
    with:
      distribution: googlecloudspanner
    secrets: inherit
    permissions: write-all
